### ISSUE TITLE
Share your work with Mattermost community?

### ISSUE THREAD

**Issue by jasonblais** [nnewman/stewie#3]
Hi @nnewman ,

Saw your work for Stewie bot and we'd love to help share it with the Mattermost community. Would you be open to sharing more about your work? https://www.mattermost.org/share-your-mattermost-projects/

Also, we'd like to welcome you to join the integrations community on our nightly builds server, if you'd like: https://pre-release.mattermost.com/core/channels/integrations

Wonderful work!

**Comment by nnewman** [comment]
@jasonblais - thanks for the recognition! I'm glad to get to share Stewie with the community!
